name: 'Release'
on:
  workflow_run:
    workflows: ["Test"]
    branches:
      - master
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && !contains(github.event.head_commit.message, 'skip ci') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: npm install
      - run: npm run build
      - name: release
        env:
          NPM_TOKEN: ${{ secrets.NPMJS_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release
